name: agent-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  guard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black isort flake8 bandit

      # Жёсткая проверка синтаксиса (если не компилится — фейл)
      - name: Syntax check (compileall)
        run: |
          python - <<'PY'
          import compileall, sys
          ok = compileall.compile_dir('.', quiet=1, force=True)
          sys.exit(0 if ok else 1)
          PY

      # Жёсткая проверка импорта основных модулей
      - name: Import smoke test
        run: |
          python - <<'PY'
          import importlib, sys
          mods = [
            "positions_guard",
            "position_manager",
            "core.predict",
            "core.market_info",
            "core.env_loader",
          ]
          for m in mods:
              try:
                  importlib.import_module(m)
                  print(f"[import OK] {m}")
              except Exception as e:
                  print(f"[import FAIL] {m}: {e}")
                  sys.exit(1)
          print("imports OK")
          PY

      # Линтеры и SAST — НЕ блокируют
      - name: Lint (non-blocking)
        run: |
          echo "flake8..."
          flake8 . || true
          echo "bandit..."
          bandit -q -r . || true
          echo "isort check..."
          isort --check-only . || true
          echo "black check..."
          black --check . || true

      - name: Auto-format (isort+black)
        run: |
          isort .
          black .


      # Авто-PR (если что-то изменили в agent-скриптах или форматтером)
      - name: Create PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: agent/fixes
          delete-branch: true
          title: "Agent: авто-правки (импорты/форматирование/починка CI)"
          commit-message: "agent: auto-fixes"
          body: |
            Авто-PR: 
            - синтаксис/импорт проверяются жёстко
            - линтеры не блокируют
            - права на PR/commit выставлены
